### ISSUE TITLE
Active nodes chart does not look right

### ISSUE THREAD

**Issue by botnumberseven** [othub-io/othub-app#38]
![image](https://github.com/user-attachments/assets/def5cd8f-06f0-4d3a-87d5-c0db67f53328)

tooltip says Base 26 nodes, but axis says 80+ something

you have it like stacked lines, but it's confusing, it looks like number of Base nodes go down, when in reality it does not

**Comment by CosmiCloud** [comment]
fixed with https://github.com/othub-io/othub-app/pull/39
