### ISSUE TITLE
Node page - clicking on a node name shows details of another node

### ISSUE THREAD

**Issue by Valcyclovir** [othub-io/othub-app#8]
https://github.com/user-attachments/assets/a5c49ad0-bd54-4e71-b49c-1f23d4b1449b

When selecting a node from the list of Nodes, it sometimes shows the details of a different node. 

This bug happens whether you select All Blockchains or a specific blockchain, and seems to occur on pages other than the first one.

**Comment by CosmiCloud** [comment]
Should be fixed with https://github.com/othub-io/othub-app/pull/15
